### ISSUE TITLE
US-7: As an employer, I want to be able to add and manage job postings, so the students can apply to available positions

### ISSUE THREAD

**Issue by P4SS3-P4RT0UT** [Magy2211/SOEN341_PROJECT#26]
**End user goal:** Have students apply to the job postings.

**Acceptance criteria:** The employer is able to add a job posting to the system. The employer is able to modify a job posting. The employer is able to remove a job posting. The job posting is removed from the students who applied to the job posting when an employer deletes a job posting.

**Task breakdown:**
- [x] Create a database table containing job postings information
- [x] Create a user interface for entering information about the job postings
- [x] Implement a feature to modify a job posting information in the database
- [x] #86
