### ISSUE TITLE
US-1: As a student/candidate, I to be able to manage my profile to provide accurate information to the employer

### ISSUE THREAD

**Issue by Magy2211** [Magy2211/SOEN341_PROJECT#3]
**End user goal**: create a profile and upload their CV 

**Acceptance criteria**: If the website provides a platform to create a profile and add a CV to the profile. 

**Task breakdown:**
- [x] Implement a registration and login system
- [x] Create a databse table containing students personal information
- [x] Create user interface for entering personal information and viewing the information
- [x] Implement a feature to modify a student information in the database

**Comment by P4SS3-P4RT0UT** [comment]
Reformulated the user story to match with main feature
