### ISSUE TITLE
US-12: As a student/candidate/employer, I want to be able to provide feedback to the development team to suggest new features

### ISSUE THREAD

**Issue by P4SS3-P4RT0UT** [Magy2211/SOEN341_PROJECT#63]
**End user goal:** Suggesting useful features for the website to the development team.
**Acceptance criteria:** The development team can view the feedback forms submitted by the users.

**Task breakdown**:

- [x] Create a user interface for the students and employers to send feedback
- [x] Create a database to store the user feedback forms
- [x] Implement a feature for the admin to view the feedback forms
